# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/191CqGgmSP4Tg54ie6551-1gw69Le0D0V
"""

#import the necessary libraries

import cv2 as cv
import openpyxl

# certificate
certificate = '/content/drive/MyDrive/automated certificate generator/certificate.png'

# xl file
input_file = '/content/drive/MyDrive/automated certificate generator/input.xlsx'

# Output Paths
output_path = '/content/drive/MyDrive/automated certificate generator/output'

# Setting the font size and font
# colour
font_size = 1
font_color = (0,0,0)

# Coordinates on the certificate where
# will be printing the name (set
# according to your own template)
coordinate_y_adjustment = 15
coordinate_x_adjustment = 7

# loading the details.xlsx workbook
# and grabbing the active sheet
obj = openpyxl.load_workbook(input_file)
sheet = obj.active

# printing for the first 10 names in the
# excel sheet
for i in range(1,11):

    # grabs the row=i and column=1 cell
    # that contains the name value of that
    # cell is stored in the variable certi_name
    get_name = sheet.cell(row = i ,column = 1)
    certi_name = get_name.value
    # print(certi_name)

    # read the certificate template
    img = cv.imread(certificate)

    # choose the font from opencv
    font = cv.FONT_HERSHEY_SCRIPT_COMPLEX
    # print(font)

    # get the size of the name to be
    # printed
    text_size = cv.getTextSize(certi_name, font, font_size, 1)[0]
    # print(text_size)

    # get the (x,y) coordinates where the
    # name is to written on the template
    # The function cv.putText accepts only
    # integer arguments so convert it into 'int'.
    text_x = (img.shape[1] - text_size[0]) / 2 + coordinate_x_adjustment
    text_y = (img.shape[0] + text_size[1]) / 2 - coordinate_y_adjustment
    text_x = int(text_x)
    text_y = int(text_y)
    # print(text_x, text_y)
    cv.putText(img, certi_name,
              (text_x ,text_y),
              font,
              font_size,
              font_color, 1)

    # # Output path along with the name of the
    # # certificate generated
    certi_path = output_path + '/certi' + str(i) + '.png'

    # # Save the certificate
    cv.imwrite(certi_path,img)